title:  FrontFest
tagline:  blog

# Authors documented under _data

# google-ID: 'UA-80213386-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/frontfest'}
- {icon: 'twitter', link: 'https://twitter.com/frontfest'}
- {icon: 'envelope', link: 'mailto:frontfest@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
